name: shelf_gzip
description: Shelf middleware to GZIP encoding responses, with compression level and compression scope by content-type.
version: 4.1.0
homepage: https://github.com/johnpryan/shelf_gzip

environment:
  sdk: '>=2.13.0 <4.0.0'

dependencies:
  shelf: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
