name: shelf_gzip
description: Shelf middleware to GZIP responses
version: 3.0.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/shelf_gzip

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0
